security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  providers:
    from_database:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: true
      logout:
        path: /logout
        target: /login

      form_login:
        login_path: app_login
        check_path: app_login

  access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/article, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/article, roles: IS_AUTHENTICATED_FULLY }
